***
Hi and welcome to this Python basics course! 
<br>
<br>
This crash course will serve as an introduction for courses where we will use python as our programming language and will be a way for you to get introduced into it.
***

### Numpy

NumPy is a Python library for numerical computing that provides efficient and convenient array operations and linear algebra routines.
<br>
<br>
Numpy is an external library widely used to deal with arrays, matrixes and tensors in Python - this is an external library so we have to import it to be able to use its functions:

In [1]:
import numpy as np

A simple one dimensional array:

In [2]:
np.array(1)

array(1)

In [3]:
my_array = np.array([1])
my_array.shape

(1,)

In [4]:
my_array = np.array([1,1])
my_array.shape

(2,)

In [5]:
my_array = np.array([[1,2],[3,4]])
my_array.shape

(2, 2)

In [ ]:
my_array[:,:] # my_array[row,column]

array([[1, 2],
       [3, 4]])

In [ ]:
my_array[1,1] # array[1,1] element

np.int64(4)

In [10]:
my_array[0,:]

array([1, 2])

In [11]:
my_array[:,1]

array([2, 4])

In [ ]:
np.zeros([1,2]) # array with one row and two columns

array([[0., 0.]])

In [13]:
np.zeros([1,2]).shape

(1, 2)

In [14]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros([2,2]).shape

(2, 2)

In [16]:
np.zeros([2,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.ones([2,3]) # create a 2x3 array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones_array = np.ones([2,3])
ones_array[1,1] = 10 # change the value of the second element of the second row
ones_array

array([[ 1.,  1.,  1.],
       [ 1., 10.,  1.]])

A one dimensional array with two elements:

In [3]:
np.array([1,2])

array([1, 2])

A two dimensional array:

In [4]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

We can check dimensions using the shape attribute:

In [5]:
np.array([[1,2],[2,3]]).shape

(2, 2)

`Numpy zeros` and `numpy ones` create arrays of 0's or 1's with a specific shape:

In [6]:
np.zeros([1,2])

array([[0., 0.]])

Arrays do not stop at 2 dimensions!

In [7]:
np.zeros([1,2,4]).shape

(1, 2, 4)

In [8]:
np.ones([1,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

We can access numpy arrays like we access other python objects such as lists:

In [9]:
example_array = np.array([[1,2],[3,4]])

The only difference is that we are now indexing multi-dimensional objects using `,`:

In [15]:
example_array[1,1]

4

In [16]:
example_array[1,0]

3

In [17]:
example_array[0,1]

2

In [14]:
example_array[0,0]

1

### Pandas

Pandas is a Python library for data manipulation and analysis that provides powerful data structures, such as dataframes and series, and a variety of functions and methods for handling and processing data.

In [1]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
pd.DataFrame(data=np.ones((3, 3)), columns=['a', 'b', 'c'])

     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

In [5]:
pd.DataFrame(data=np.array([[1,2],[3,4]]))

   0  1
0  1  2
1  3  4

In [6]:
pd.DataFrame(data=np.array([[1,2],[3,4]]), columns=['col1', 'col2'], index=['row1','row2'])

      col1  col2
row1     1     2
row2     3     4

In [7]:
my_df = pd.DataFrame(data=np.array([[1,2],[3,4]]), columns=['col1', 'col2'], index=['row1','row2'])

In [8]:
my_df.iloc[:,:]

      col1  col2
row1     1     2
row2     3     4

In [9]:
my_df.iloc[1,1]

np.int64(4)

In [10]:
my_df.iloc[:,1]

row1    2
row2    4
Name: col2, dtype: int64

In [11]:
my_df.loc['row1']

col1    1
col2    2
Name: row1, dtype: int64

In [15]:
my_df.loc['row1','col2']

np.int64(2)

In [16]:
my_df.iloc[:,1]=[100,200]

In [17]:
my_df

      col1  col2
row1     1   100
row2     3   200

In [19]:
pd.DataFrame(np.array([0,1,2]), columns=['col'], index=['A','B','C'])

   col
A    0
B    1
C    2

We can also pass lists when creating DataFrames:

In [20]:
pd.DataFrame([[0,1,2],[1,2,3]], columns=['col_1', 'col_2','col_3'], index=['A','B'])

   col_1  col_2  col_3
A      0      1      2
B      1      2      3

In [21]:
dataframe_example = (
    pd.DataFrame([[0,'A',2],[1,'B',3]], columns=['col_1', 'col_2','col_3'], index=['A','B'])
)

To index dataframes we can use names or indexes (using either `loc` or `iloc`):

In [22]:
dataframe_example.loc[:,'col_1']

A    0
B    1
Name: col_1, dtype: int64

In [23]:
dataframe_example.iloc[:,0]

A    0
B    1
Name: col_1, dtype: int64

In [24]:
dataframe_example.loc['A',:]

col_1    0
col_2    A
col_3    2
Name: A, dtype: object

In [25]:
dataframe_example.iloc[0,:]

col_1    0
col_2    A
col_3    2
Name: A, dtype: object