In [1]:
%reload_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.style = 'default'  # This is the key fix

In [2]:
# # First, close all SQL connections
# %sql --close sqlite:///practice.db

In [3]:
# Delete the database file
!rm -f practice1.db

In [4]:
# Connect to an SQLite database (creates if doesn't exist)
%sql sqlite:///practice1.db

In [5]:
%%sql
create table Customers (CustomerID integer primary key, CustomerName text, City text);

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql 
insert into Customers(CustomerID,CustomerName,City) values (1,'ankit','kanpur'),(2,'kiio','pathankoat')

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [7]:
%sql select * from Customers;

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat

In [8]:
%sql select [CustomerID],[City] from Customers

 * sqlite:///practice1.db

   CustomerID        City
0           1      kanpur
1           2  pathankoat

In [9]:
%%sql
insert into Customers(CustomerID,CustomerName,City) values (3,'arpit','kanpur'),(4,'kiio','delhi')

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [10]:
%sql select [CustomerID],CustomerName,[City] from Customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [11]:
%sql select distinct CustomerName,City from Customers;

 * sqlite:///practice1.db

  CustomerName        City
0        ankit      kanpur
1         kiio  pathankoat
2        arpit      kanpur
3         kiio       delhi

In [12]:
%sql select distinct CustomerName from Customers;

 * sqlite:///practice1.db

  CustomerName
0        ankit
1         kiio
2        arpit

In [13]:
%sql select CustomerName,sum(CustomerID) sum_ids from Customers where CustomerName='kiio' group by CustomerName

 * sqlite:///practice1.db

  CustomerName  sum_ids
0         kiio        6

In [14]:
%sql select * from Customers order by CustomerName,City

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           3        arpit      kanpur
2           4         kiio       delhi
3           2         kiio  pathankoat

In [15]:
%sql select * from Customers order by City ASC,CustomerName Desc

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           4         kiio       delhi
1           3        arpit      kanpur
2           1        ankit      kanpur
3           2         kiio  pathankoat

In [16]:
%sql select * from Customers where CustomerName='kiio' and  City like '%h%'

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           4         kiio       delhi

In [17]:
%sql select * from Customers where not CustomerName='ankit' or  City like '_e%i'

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           3        arpit      kanpur
2           4         kiio       delhi

In [18]:
%sql select * from Customers where CustomerName='kiio' and  City not like '%e%'

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat

In [19]:
%sql select * from Customers where CustomerID not between 2 and 3

 * sqlite:///practice1.db

   CustomerID CustomerName    City
0           1        ankit  kanpur
1           4         kiio   delhi

In [20]:
%sql select * from Customers where CustomerID between 2 and 3

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           3        arpit      kanpur

In [21]:
%sql select * from Customers where CustomerID not in (2,3)

 * sqlite:///practice1.db

   CustomerID CustomerName    City
0           1        ankit  kanpur
1           4         kiio   delhi

In [22]:
%sql select * from Customers where CustomerID in (2,3)

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           3        arpit      kanpur

In [23]:
%sql select CustomerName from Customers where City is not null

 * sqlite:///practice1.db

  CustomerName
0        ankit
1         kiio
2        arpit
3         kiio

In [24]:
%sql select distinct CustomerName from Customers where City is not null

 * sqlite:///practice1.db

  CustomerName
0        ankit
1         kiio
2        arpit

In [25]:
%%sql
update Customers set CustomerName='Summi' where CustomerName='arpit';
update Customers set CustomerName='Summi', City='Hathras' where CustomerID=3;
select * from Customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        Summi     Hathras
3           4         kiio       delhi

In [26]:
%%sql
delete from Customers where CustomerID=3;
select * from Customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           4         kiio       delhi

In [27]:
%%sql
delete from Customers ;
select * from Customers

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [28]:
%sql truncate table Customers -- sqlite does not support truncate

 * sqlite:///practice1.db
(sqlite3.OperationalError) near "truncate": syntax error
[SQL: truncate table Customers]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [29]:
%sql drop table Customers

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [30]:
%sql select * from Customers

 * sqlite:///practice1.db
(sqlite3.OperationalError) no such table: Customers
[SQL: select * from Customers]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [31]:
%%sql
create table Customers (CustomerID integer primary key, CustomerName text, City text);
insert into Customers(CustomerID,CustomerName,City) values (1,'ankit','kanpur'),(2,'kiio','pathankoat'),(3,'arpit','kanpur'),(4,'kiio','delhi');
select * from Customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [32]:
%%sql
select * from Customers;

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [33]:
%sql select * from Customers order by City limit 2;

 * sqlite:///practice1.db

   CustomerID CustomerName    City
0           4         kiio   delhi
1           1        ankit  kanpur

In [34]:
%%sql
select CustomerName, sum(CustomerID) from Customers group by CustomerName having CustomerName='kiio'

 * sqlite:///practice1.db

  CustomerName  sum(CustomerID)
0         kiio                6

In [35]:
%%sql
select CustomerName, count(CustomerName) from Customers group by CustomerName having CustomerName='kiio'

 * sqlite:///practice1.db

  CustomerName  count(CustomerName)
0         kiio                    2

In [36]:
%%sql
select CustomerName, avg(CustomerID) from Customers group by CustomerName having CustomerName='kiio'

 * sqlite:///practice1.db

  CustomerName  avg(CustomerID)
0         kiio              3.0

In [37]:
%%sql
select CustomerName, max(CustomerID) [Maximum Customer ID Value] 
from Customers group by CustomerName having CustomerName='kiio'

 * sqlite:///practice1.db

  CustomerName  Maximum Customer ID Value
0         kiio                          4

In [38]:
%%sql
select * from Customers where CustomerName like '%' -- % means zero or more than zero characters searching

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [39]:
%%sql
select * from Customers where CustomerName like 'k%'

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           4         kiio       delhi

In [40]:
%%sql
-- [regex not supported in sqlite] select * from Customers where CustomerName like '%[o]%'
select * from Customers where CustomerName like '%o%'

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           4         kiio       delhi

In [41]:
%%sql
-- [regex not supported in sqlite] select * from Customers where CustomerName like '[k-o]%'
select * from Customers 
where CustomerName like 'k%' 
   or CustomerName like 'l%' 
   or CustomerName like 'm%' 
   or CustomerName like 'n%' 
   or CustomerName like 'o%'

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           4         kiio       delhi

In [42]:
%%sql
select * from Customers 
where CustomerName glob '[k-o]*'

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           4         kiio       delhi

In [43]:
%%sql
select * from Customers where CustomerName glob '[^k-o]*'

 * sqlite:///practice1.db

   CustomerID CustomerName    City
0           1        ankit  kanpur
1           3        arpit  kanpur

In [44]:
%%sql

-- second max customer id

select CustomerName, CustomerID from Customers 
where CustomerID not in (select max(CustomerID) from Customers) order by CustomerID desc limit 1

 * sqlite:///practice1.db

  CustomerName  CustomerID
0        arpit           3

In [45]:
%%sql
select CustomerID+5 as "New Customer ID" from Customers

 * sqlite:///practice1.db

   New Customer ID
0                6
1                7
2                8
3                9

In [46]:
%%sql
select CustomerID+5 as "New Customer ID", CustomerName+' and '+City as "CustomerName and City Name" 
from Customers

 * sqlite:///practice1.db

   New Customer ID  CustomerName and City Name
0                6                           0
1                7                           0
2                8                           0
3                9                           0

SQLite uses the || operator for string concatenation instead of the + operator.

In [47]:
%%sql
SELECT CustomerID+5 as "New Customer ID", 
       CustomerName || ' and ' || City as "CustomerName and City Name" 
FROM Customers

 * sqlite:///practice1.db

   New Customer ID CustomerName and City Name
0                6           ankit and kanpur
1                7        kiio and pathankoat
2                8           arpit and kanpur
3                9             kiio and delhi

In [48]:
%%sql
create table Orders (CustomerID int primary key, ProductName varchar(20), ProductID varchar(20));
insert into Orders values (1,'Washing Machine', 567),(2,'TV', 768),(5,'Radio', 786),(6,'Computer', 987);
select * from Customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [49]:
%sql select * from Orders;

 * sqlite:///practice1.db

   CustomerID      ProductName ProductID
0           1  Washing Machine       567
1           2               TV       768
2           5            Radio       786
3           6         Computer       987

### joins

In [50]:
%%sql
-- Check Customers table structure
PRAGMA table_info(Customers);

-- Check Orders table structure
PRAGMA table_info(Orders);

 * sqlite:///practice1.db

   cid         name         type  notnull dflt_value  pk
0    0   CustomerID          INT        0       None   1
1    1  ProductName  varchar(20)        0       None   0
2    2    ProductID  varchar(20)        0       None   0

In [51]:
%%sql
select C.CustomerID,C.CustomerName,O.CustomerID,O.ProductName 
from Customers C inner join Orders O on C.CustomerID=O.CustomerID

 * sqlite:///practice1.db

   CustomerID CustomerName  CustomerID      ProductName
0           1        ankit           1  Washing Machine
1           2         kiio           2               TV

In [52]:
%%sql
select C.CustomerID,C.CustomerName,O.CustomerID,O.ProductName 
from Customers C right join Orders O on C.CustomerID=O.CustomerID

 * sqlite:///practice1.db

   CustomerID CustomerName  CustomerID      ProductName
0         1.0        ankit           1  Washing Machine
1         2.0         kiio           2               TV
2         NaN         None           5            Radio
3         NaN         None           6         Computer

In [53]:
%%sql
select C.CustomerID,C.CustomerName,O.CustomerID,O.ProductName 
from Customers C left join Orders O on C.CustomerID=O.CustomerID

 * sqlite:///practice1.db

   CustomerID CustomerName  CustomerID      ProductName
0           1        ankit         1.0  Washing Machine
1           2         kiio         2.0               TV
2           3        arpit         NaN             None
3           4         kiio         NaN             None

In [54]:
%%sql
select C.CustomerID,C.CustomerName,O.CustomerID,O.ProductName 
from Customers C full outer join Orders O on C.CustomerID=O.CustomerID

 * sqlite:///practice1.db

   CustomerID CustomerName  CustomerID      ProductName
0         1.0        ankit         1.0  Washing Machine
1         2.0         kiio         2.0               TV
2         3.0        arpit         NaN             None
3         4.0         kiio         NaN             None
4         NaN         None         5.0            Radio
5         NaN         None         6.0         Computer

In [55]:
%%sql
select C1.CustomerID,C1.CustomerName,C2.CustomerID,C2.City 
from Customers C1 inner join Customers C2 on C1.CustomerID=C2.CustomerID

 * sqlite:///practice1.db

   CustomerID CustomerName  CustomerID        City
0           1        ankit           1      kanpur
1           2         kiio           2  pathankoat
2           3        arpit           3      kanpur
3           4         kiio           4       delhi

In [56]:
%%sql
select C.CustomerID,C.CustomerName,O.CustomerID,O.ProductName from Customers C cross join Orders O

 * sqlite:///practice1.db

    CustomerID CustomerName  CustomerID      ProductName
0            1        ankit           1  Washing Machine
1            1        ankit           2               TV
2            1        ankit           5            Radio
3            1        ankit           6         Computer
4            2         kiio           1  Washing Machine
5            2         kiio           2               TV
6            2         kiio           5            Radio
7            2         kiio           6         Computer
8            3        arpit           1  Washing Machine
9            3        arpit           2               TV
10           3        arpit           5            Radio
11           3        arpit           6         Computer
12           4         kiio           1  Washing Machine
13           4         kiio           2               TV
14           4         kiio           5            Radio
15           4         kiio           6         Computer

### union,intersection

In [57]:
%%sql
select CustomerID from Customers where CustomerID not IN (2,4)
union all 
select CustomerID from Customers where CustomerID not IN (1,3)

 * sqlite:///practice1.db

   CustomerID
0           1
1           3
2           2
3           4

In [58]:
%%sql
select CustomerID from Customers where CustomerID not IN (2,4)
union  
select CustomerID from Customers where CustomerID IN (1,3)

 * sqlite:///practice1.db

   CustomerID
0           1
1           3

In [59]:
%%sql
select CustomerID from Customers where CustomerID not IN (3,4)
intersect
select CustomerID from Customers where CustomerID IN (1,3)

 * sqlite:///practice1.db

   CustomerID
0           1

In [60]:
%sql select * from Customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [61]:
%%sql
select City,sum(CustomerID) Sum_ID from Customers group by City having City <> 'kanpur' order by Sum_ID desc

 * sqlite:///practice1.db

         City  Sum_ID
0       delhi       4
1  pathankoat       2

In [62]:
%%sql
-- The EXISTS operator is used to test for the existence of any record in a subquery.

-- The EXISTS operator returns TRUE if the subquery returns one or more records.

select * from Customers where exists (select * from Customers where City='kanpur')

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [63]:
%%sql
select * from Customers where not exists (select * from Customers where City='lucknow')

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [64]:
%%sql
select * from Customers where not exists (select * from Customers where City='kanpur')

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [65]:
%%sql
select * from Customers where CustomerID= ANY(select CustomerID from Customers where CustomerName='kiio')

 * sqlite:///practice1.db
(sqlite3.OperationalError) near "select": syntax error
[SQL: select * from Customers where CustomerID= ANY(select CustomerID from Customers where CustomerName='kiio')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

 SQLite does not support the ANY operator. SQLite has limited support for subquery operators compared to other SQL databases.

In [66]:
%%sql
SELECT * FROM Customers 
WHERE CustomerID IN (SELECT CustomerID FROM Customers WHERE CustomerName = 'kiio');

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat
1           4         kiio       delhi

In [67]:
%%sql
select *  from Customers where CustomerID= ALL(select CustomerID from Customers where CustomerName='kiio')

 * sqlite:///practice1.db
(sqlite3.OperationalError) near "ALL": syntax error
[SQL: select *  from Customers where CustomerID= ALL(select CustomerID from Customers where CustomerName='kiio')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

SQLite does not support the ALL operator. SQLite has limited subquery operator support compared to other SQL databases.

In [68]:
%%sql
SELECT * FROM Customers 
WHERE CustomerID IN (SELECT CustomerID FROM Customers WHERE CustomerName = 'kiio')
AND (SELECT COUNT(DISTINCT CustomerID) FROM Customers WHERE CustomerName = 'kiio') = 1;

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [69]:
%%sql
SELECT * FROM Customers 
WHERE CustomerID = (SELECT CustomerID FROM Customers WHERE CustomerName = 'kiio' LIMIT 1);

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           2         kiio  pathankoat

insert recrds from one table to another table even if it is not existed or existed but duplicate records are ignored.

In [70]:
%%sql
select * into [New Customers] from Customers

 * sqlite:///practice1.db
(sqlite3.OperationalError) near "into": syntax error
[SQL: select * into [New Customers] from Customers]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The error occurs because SQLite doesn't support the SELECT INTO syntax. SQLite uses a different approach for creating a new table from an existing table.

In [71]:
%%sql
CREATE TABLE "New Customers" AS 
SELECT * FROM Customers

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [72]:
%%sql
select * from [New Customers]

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [73]:
%%sql
select * from "New Customers"

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

In [74]:
%%sql
create table New_Customers in 'backup.mdb' as select * from Customers

 * sqlite:///practice1.db
(sqlite3.OperationalError) near "in": syntax error
[SQL: create table New_Customers in 'backup.mdb' as select * from Customers]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The error occurs because the IN 'backup.mdb' clause is not valid SQLite syntax. You're trying to create a table in a different database file, but SQLite doesn't support that syntax.

In [76]:
%%sql
-- Attach the backup database
ATTACH DATABASE 'backup.mdb' AS backup_db;

-- Create the table in the attached database
CREATE TABLE backup_db.New_Customers AS 
SELECT * FROM Customers;

-- Detach when done (optional)
DETACH DATABASE backup_db;

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [78]:
%%sql
-- Attach the backup database
ATTACH DATABASE 'backup.mdb' AS backup;

-- Query from the backup database
SELECT * FROM backup.New_Customers;

-- With LIMIT if you have many rows
SELECT * FROM backup.New_Customers LIMIT 10;

-- Count rows
SELECT COUNT(*) FROM backup.New_Customers;

-- Detach when done
DETACH DATABASE backup;

 * sqlite:///practice1.db
(sqlite3.OperationalError) database backup is locked
[SQL: -- Detach when done
DETACH DATABASE backup;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [79]:
%%sql
-- First, check if database is already attached
SELECT name FROM pragma_database_list;

 * sqlite:///practice1.db

     name
0    main
1  backup

In [81]:
%%sql
-- Backup is already attached (as shown in your query), so just query it
SELECT * FROM backup.New_Customers LIMIT 10;

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi

copy the data from one table to another table which should be existed already

In [82]:
%%sql
insert into new_customers select * from Customers

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [83]:
%%sql
select * from new_customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City
0           1        ankit      kanpur
1           2         kiio  pathankoat
2           3        arpit      kanpur
3           4         kiio       delhi
4           1        ankit      kanpur
5           2         kiio  pathankoat
6           3        arpit      kanpur
7           4         kiio       delhi

#### CASE Expression

-- when both cases are true then both statements executed and else statement executed where when condition is false

-- only one column name can be put in all the when conditions

In [84]:
%%sql
select *, 
case
when CustomerName='kiio' then 'this is kiio'
when CustomerName='ankit' then 'this is me'
else 'this is arpit'
end as Msg
from Customers

 * sqlite:///practice1.db

   CustomerID CustomerName        City            Msg
0           1        ankit      kanpur     this is me
1           2         kiio  pathankoat   this is kiio
2           3        arpit      kanpur  this is arpit
3           4         kiio       delhi   this is kiio

In [ ]:
%%sql
select *,case when CustomerID in (1,2) then 'this is me' end as msg 
into experiment  from Customers

 * sqlite:///practice1.db
(sqlite3.OperationalError) near "into": syntax error
[SQL: select *,case when CustomerID in (1,2) then 'this is me' end as msg into experiment  from Customers]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The error occurs because SQLite doesn't support the SELECT INTO syntax. This is a SQL Server/Microsoft SQL syntax, not SQLite.

In [86]:
%%sql
CREATE TABLE experiment AS
SELECT *,
       CASE 
         WHEN CustomerID IN (1, 2) THEN 'this is me' 
         ELSE NULL 
       END as msg
FROM Customers;

 * sqlite:///practice1.db

Empty DataFrame
Columns: []
Index: []

In [87]:
%%sql
select * from experiment

 * sqlite:///practice1.db

   CustomerID CustomerName        City         msg
0           1        ankit      kanpur  this is me
1           2         kiio  pathankoat  this is me
2           3        arpit      kanpur        None
3           4         kiio       delhi        None

In [88]:
%%sql
select * from experiment order by (case when msg is null then CustomerName else City end) Desc

 * sqlite:///practice1.db

   CustomerID CustomerName        City         msg
0           2         kiio  pathankoat  this is me
1           4         kiio       delhi        None
2           1        ankit      kanpur  this is me
3           3        arpit      kanpur        None

In [89]:
%%sql
select ISNULL(msg,'this is not null') as Message from experiment

 * sqlite:///practice1.db
(sqlite3.OperationalError) near "ISNULL": syntax error
[SQL: select ISNULL(msg,'this is not null') as Message from experiment]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The error occurs because ISNULL() is a SQL Server function, not SQLite. SQLite uses different functions for handling NULL values.

In [90]:
%%sql
SELECT IFNULL(msg, 'this is null') as Message FROM experiment;

 * sqlite:///practice1.db

        Message
0    this is me
1    this is me
2  this is null
3  this is null

In [91]:
%%sql
select COALESCE(msg,'this is not null') as Message from experiment

 * sqlite:///practice1.db

            Message
0        this is me
1        this is me
2  this is not null
3  this is not null

### Stored Procedure