In [5]:
import pandas as pd
import numpy as np

In [6]:
iris=pd.read_csv("Iris.csv")

In [7]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

#### replace factors with numbers

In [8]:
species_map = {"Iris-setosa": 1, "Iris-versicolor": 2, "Iris-virginica": 3}
iris['Species'] = iris['Species'].map(species_map).astype(int)

In [9]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

#### change dataframe (pd) to numpy array

In [10]:
#change dataframe to array
datatrain_array = iris.values

#split x and y (feature and target)
xtrain = datatrain_array[:,:4]
ytrain = datatrain_array[:,4]

### Set up ANN

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
torch.manual_seed(1234)

In [12]:
#hyperparameters
hl = 10
lr = 0.01
num_epoch = 500

In [13]:
#build model
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, hl) ##4 predictors
        self.fc2 = nn.Linear(hl, 3) ##3 classes

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
net = Net() ##variable to store the ANN model

In [14]:
#choose optimizer and loss function
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), lr=lr)

In [15]:
for epoch in range(num_epoch):
    X = Variable(torch.Tensor(xtrain).float()) ##convert xs to tensor
    Y = Variable(torch.Tensor(ytrain).long())

    #feedforward - backprop
    optimizer.zero_grad() ##we need to set the gradients to zero before starting to do backpropragation 
    out = net(X)
    loss = criterion(out, Y)
    loss.backward()
    optimizer.step()

    if (epoch) % 50 == 0:
        print ('Epoch [%d/%d] Loss: %.4f' 
                   %(epoch+1, num_epoch, loss.item()))

Epoch [1/500] Loss: 1.9714
Epoch [51/500] Loss: 0.7951
Epoch [101/500] Loss: 0.7205
Epoch [151/500] Loss: 0.5892
Epoch [201/500] Loss: 0.5403
Epoch [251/500] Loss: 0.5100
Epoch [301/500] Loss: 0.4891
Epoch [351/500] Loss: 0.4739
Epoch [401/500] Loss: 0.4590
Epoch [451/500] Loss: 0.4419